# Generated by Django 4.0.2 on 2022-04-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_userbookshelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookshelf',
            name='novels',
            field=models.ManyToManyField(related_name='bookshelf', to='novel.Novel'),
        ),
    ]
