# Generated by Django 4.0.2 on 2022-03-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='book_image',
            field=models.ImageField(default='some', upload_to='novel/img/book_cover'),
            preserve_default=False,
        ),
    ]
