# Generated by Django 4.0.2 on 2022-03-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_novel_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='description',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='novel',
            name='book_image',
            field=models.ImageField(upload_to='./static/novel/img/book_cover'),
        ),
    ]
