# Generated by Django 4.0.2 on 2022-04-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_userbookshelf_novels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookshelf',
            name='novels',
            field=models.ManyToManyField(blank=True, related_name='bookshelf', to='novel.Novel'),
        ),
    ]
