# Generated by Django 4.0.2 on 2022-03-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0007_alter_novel_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='createrd_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
