# Generated by Django 4.0.2 on 2022-05-02 10:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novel', '0008_alter_comment_active_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='CommentLike',
        ),
    ]
