# Generated by Django 4.0.2 on 2022-03-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0008_rename_createrd_at_novel_created_at_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='tags',
            field=models.ManyToManyField(related_name='novel', to='novel.Tag'),
        ),
    ]
