# Generated by Django 4.0.2 on 2022-03-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0009_alter_novel_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novel',
            options={'ordering': ['-created_at']},
        ),
    ]
