# Generated by Django 4.0.2 on 2022-05-03 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novel', '0009_rename_like_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='users',
            field=models.ManyToManyField(related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
