# Generated by Django 4.0.2 on 2022-03-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0010_alter_novel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
