# Generated by Django 4.0.6 on 2022-07-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0011_daynumber_userip_visitnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
