# Generated by Django 4.0.2 on 2022-03-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='./authentication/img/defaultUserImage.svg', upload_to=''),
        ),
    ]
