# Generated by Django 4.0.2 on 2022-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='defaultUserImage.svg', upload_to=''),
        ),
    ]
