# Generated by Django 4.0.2 on 2022-03-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='defaultUserImage.svg', upload_to='user-images'),
        ),
    ]
