# Generated by Django 4.0.2 on 2022-03-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_email_alter_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_email',
            field=models.BooleanField(default=False, help_text='If user verified email', verbose_name='active email'),
        ),
    ]
