# Generated by Django 4.0.2 on 2022-04-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_is_active_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='./authentication/defaultUserImage.svg', upload_to='./authentication/user-images'),
        ),
    ]
